include:
  - https://cnb.cool/1024hub/workflow/-/blob/master/pipeline/deploy/be-go-single.yml

# AI 汇报流水线公共 stages 定义
.ai-report-stages: &ai-report-stages
  stages:
    - name: Install deps and generate report
      image: node:20
      timeout: 20m
      script:
        - |
          set -eu
          apt-get update -y >/dev/null
          DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends git curl ca-certificates tzdata jq >/dev/null
          git --version
          if ! command -v opencode >/dev/null 2>&1; then
            (curl -fsSL https://opencode.ai/install | bash) || true
          fi
          if ! command -v opencode >/dev/null 2>&1; then
            npm i -g opencode-ai || true
            export PATH="$(npm root -g)/.bin:$PATH"
          fi
          bash scripts/ai-report-pipeline.sh
          if [ -d reports ] && ls -1 reports/*.md >/dev/null 2>&1; then
            ls -lah reports
            echo "----- 汇报预览 -----"
            head -n 80 $(ls -1t reports/*.md | head -n 1) || true
            echo "----- 预览结束 -----"
          else
            echo "no report generated" >&2
          fi

# AI 汇报流水线公共 imports 定义
.ai-report-imports: &ai-report-imports
  imports:
    - ./.cnb/ai-report-pipeline.env.yml
    - https://cnb.cool/1024hub/Deploy/PlaneCabbConf/-/blob/main/env.yml

# ============================================================
# 定时任务 & 手动触发
# ============================================================

main:
  # 日报：每天 03:00 (Asia/Shanghai)
  "crontab: 0 3 * * *":
    - name: daily-opencode-report
      <<: *ai-report-imports
      env:
        REPORT_TIMEFRAME: "yesterday"
      <<: *ai-report-stages

  # 手动触发（dispatch）
  dispatch:
    - name: manual-opencode-report
      <<: *ai-report-imports
      env:
        REPORT_TIMEFRAME: "yesterday"
      <<: *ai-report-stages

"**":
  # Web 按钮手动触发
  web_trigger_daily_report:
    - name: web-manual-opencode-report
      <<: *ai-report-imports
      env:
        REPORT_TIMEFRAME: "yesterday"
      <<: *ai-report-stages

  # 周报：每周一 05:00 (Asia/Shanghai)
  "crontab: 0 5 * * 1":
    - name: weekly-opencode-report
      <<: *ai-report-imports
      env:
        REPORT_TIMEFRAME: "last_week"
      <<: *ai-report-stages

  # 月报：每月1号 01:00 (Asia/Shanghai)
  "crontab: 0 1 1 * *":
    - name: monthly-opencode-report
      <<: *ai-report-imports
      env:
        REPORT_TIMEFRAME: "last_month"
      <<: *ai-report-stages
